[package]
name = "native"
version = "0.1.0"
edition = "2024"

[lib]
name = "native"
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
anyhow = "1.0"
image = "0.24"
once_cell = "1.18"
log = "0.4"
byteorder = "1.5"
